### ISSUE TITLE
不支持Laravel5.5 

### ISSUE THREAD

**Issue by Nash-x9** [moell-peng/mojito#14]
![image](https://user-images.githubusercontent.com/12541919/55380191-0ae57580-5552-11e9-86d5-a49732d8a1ec.png)

**Comment by moell-peng** [comment]
支持的。 laravel5.5 你安装1.0.* 版本

**Comment by Nash-x9** [comment]
我安装得就是1.0.*
composer require moell-peng/mojito 1.0.*

**Comment by Nash-x9** [comment]
> 支持的。 laravel5.5 你安装1.0.* 版本

您看我截图  截图中是composer require moell-peng/mojito 1.0
后来我改用
```
composer require moell-peng/mojito 1.0.*
```
也不可以

**Comment by moell-peng** [comment]
composer require moell/mojito=1.0.*

**Comment by Nash-x9** [comment]
> composer require moell/mojito=1.0.*

![image](https://user-images.githubusercontent.com/12541919/55385343-7aae2d00-555f-11e9-9f56-1a153a234b14.png)

**Comment by moell-peng** [comment]
造成这个问题是因为random_compat这个组件版本有些问题。 你直接写到你composer.json中，composer update 吧 。

**Comment by Nash-x9** [comment]
> 造成这个问题是因为random_compat这个组件版本有些问题。 你直接写到你composer.json中，composer update 吧 。

嗯 可以了。这个要不要在ReadMe中写一下？
感谢！

**Comment by moell-peng** [comment]
@Nash-x9  后续我加上，不知道为啥random_compat 会发布一个v9.99.99 版本
