### ISSUE TITLE
default password change error

### ISSUE THREAD

**Issue by lonycn** [moell-peng/mojito#16]
cant change default password by `secret` :(
![image](https://user-images.githubusercontent.com/29355918/64930798-8324c680-d866-11e9-9f87-81998612066b.png)

**Comment by moell-peng** [comment]
多谢反馈，我后续版本调整一下， 目前你可以通过 php artisan tinker 去修改一下。

**Comment by moell-peng** [comment]
最新2.0 版本支持6位密码修改
