### ISSUE TITLE
php artisan db:seed --class="Moell\Mojito\Database\MojitoTableSeeder"

### ISSUE THREAD

**Issue by crabbossz** [moell-peng/mojito#19]
at /Users/zhangfan/project/php/laravel58/vendor/moell/mojito/src/Database/MojitoTableSeeder.php:215
    211|      * @author moell<moel91@foxmail.com>
    212|      */
    213|     private function createdAdminUser()
    214|     {
  > 215|         AdminUserFactory::adminUser()->truncate();
    216|
    217|         AdminUserFactory::adminUser()->create([
    218|             'name' => 'admin',
    219|             'email' => 'admin@gmail.com',

  Exception trace:

  1   Moell\Mojito\Database\MojitoTableSeeder::createdAdminUser()
      /Users/zhangfan/project/php/laravel58/vendor/moell/mojito/src/Database/MojitoTableSeeder.php:197

  2   Moell\Mojito\Database\MojitoTableSeeder::run()
      /Users/zhangfan/project/php/laravel58/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by moell-peng** [comment]
laravel 什么版本， 错误有更详细的吗？
