### ISSUE TITLE
最新版数据库迁移报错

### ISSUE THREAD

**Issue by wuli08** [moell-peng/mojito#23]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

**Comment by moell-peng** [comment]
@wuli08 这个主要是你的MySQL 版本比较低造成的，或使用此方法来解决 [https://laravel-news.com/laravel-5-4-key-too-long-error](https://laravel-news.com/laravel-5-4-key-too-long-error)
