### ISSUE TITLE
CSRF token mismatch.

### ISSUE THREAD

**Issue by yunfeiboy** [moell-peng/mojito#25]
\Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful::class,这个有什么用，增加了这个，登录报错，移除才能登录

`{message: "CSRF token mismatch.", exception: "Symfony\Component\HttpKernel\Exception\HttpException",…}
exception: "Symfony\Component\HttpKernel\Exception\HttpException"
file: "/Users/admin/code/laravel8/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
line: 369`

**Comment by moell-peng** [comment]
laravel 什么版本，目前还未测试 8.0 兼容性， Sanctum 的使用你可以看看官方文档

**Comment by yunfeiboy** [comment]
> laravel 什么版本，目前还未测试 8.0 兼容性， Sanctum 的使用你可以看看官方文档

 ➜  laravel8 php artisan -V
Laravel Framework 8.22.1
我看你写了大于7 ,是高版本

**Comment by moell-peng** [comment]
@yunfeiboy 我记错了。我这边也有8.0的项目， 正常运行， 你的报错是 CSRF 有问题，前后端分离项目不需要 CSRF, 注意你配置的中间件， 可以按照这个方向排查下。

**Comment by yunfeiboy** [comment]
> @yunfeiboy我记错了。我这边也有8.0的项目，正常运行，你的报错是CSRF有问题，前分离项目不需要CSRF，注意您配置的中间件，可以按照这个方向排查下。

还有这个菜单权限也不对的样子，估计是我不会用，能做个说明或者文档吗？Laravel-permission 插件部分还是能看懂

**Comment by moell-peng** [comment]
@yunfeiboy 用户和角色关联权限，权限再和菜单关联，菜单你自己添加前端的路由，然后再关联后端权限名即可。

**Comment by yunfeiboy** [comment]
> @yunfeiboy 用户和角色关联权限，权限再和菜单关联，菜单你自己添加前端的路由，然后再关联后端权限名即可。

非常感谢大佬指点，我也是跟了一下源码，才发现的 MenuController my

**Comment by yunfeiboy** [comment]
> @yunfeiboy 用户和角色关联权限，权限再和菜单关联，菜单你自己添加前端的路由，然后再关联后端权限名即可。

laravel8 高版本确实有问题，可以更新一下

**Comment by moell-peng** [comment]
需要配置 sanctum.stateful 或不用localhost 访问即可
