### ISSUE TITLE
请问哪时能更新下依赖吗？增加对 PHP8 和 Laravel8 的支持

### ISSUE THREAD

**Issue by Sy-Dante** [moell-peng/mojito#28]

**Comment by moell-peng** [comment]
我当前无 PHP8 环境， 我后续测试下兼容性后发布。
你可以试试修改moell/composer.json
```
 "require": {
        "php": "^7.2.0|^8.0",
        "spatie/laravel-permission": "~3.2",
        "laravel/sanctum": "^2.4"
    },
```
如果能能运行，麻烦告诉我一下。

**Comment by Sy-Dante** [comment]
> 我当前无 PHP8 环境， 我后续测试下兼容性后发布。 你可以试试修改moell/composer.json
> 
> ```
>  "require": {
>         "php": "^7.2.0|^8.0",
>         "spatie/laravel-permission": "~3.2",
>         "laravel/sanctum": "^2.4"
>     },
> ```
> 
> 如果能能运行，麻烦告诉我一下。

嗯，好的，我周一会部署测试，如果运行没问题我也可以提 PR

**Comment by moell-peng** [comment]
@Sy-Dante 已发布新版本

**Comment by Sy-Dante** [comment]
> @Sy-Dante 已发布新版本

感谢！
