### ISSUE TITLE
Readme 未提及对sanctum 有依赖，composer.json也没

### ISSUE THREAD

**Issue by sicaboy** [moell-peng/mojito#36]
Readme 未提及对sanctum 有依赖，composer.json也没

**Comment by moell-peng** [comment]
@sicaboy  compose.json 有要求 "laravel/sanctum": "^2.4|^3.2"，是在Laravel 11 中出现问题的吗？

**Comment by sicaboy** [comment]
> @sicaboy compose.json 有要求 "laravel/sanctum": "^2.4|^3.2"，是在Laravel 11 中出现问题的吗？

哦的确composer.json里有，抱歉我疏忽了

我按照Readme在全新的laravel 10 上安装了mojito，但是出现错误：Call to a member function hasPermissionTo() on null
vendor / moell / mojito / src / Http / Middleware / Authenticate.php : 21
```
if (Auth::user()->hasPermissionTo($permission))
```

我部署在服务器上了，我感觉我可能少了登录组件
https://api.2b.au/

**Comment by moell-peng** [comment]
请确定是否执行了 `php artisan mojito:install`

确定mojito.php配置文件是否的模型是否是默认配置，如果是自定义的模型，请继承 https://github.com/moell-peng/mojito/blob/master/src/Models/User.php

**Comment by sicaboy** [comment]
<img width="292" alt="image" src="https://github.com/user-attachments/assets/57dc70e3-e072-455a-9ed9-224f96580dfe" />
是的 install和 migration都执行了

**Comment by sicaboy** [comment]
Kernel里去掉        'mojito.permission' => \Moell\Mojito\Http\Middleware\Authenticate::class, 就可以访问了。
我再研究研究。
