### ISSUE TITLE
你的数据迁移文件执行的时候有很多错误,

### ISSUE THREAD

**Issue by fuchen2020** [moell-peng/mojito#4]
是否是我mysql版本低了的原因,能否附一个sql 文件,

**Comment by moell-peng** [comment]
@fuchen2020  mysql 最低版本应该是5.7 , 你可以贴出你的报错我分析一下。sql 文件你可以给我发邮件或者加我微信获取  https://moell-peng.github.io/mojito-doc/#/%E7%AE%80%E4%BB%8B?id=%E4%BA%A4%E6%B5%81
