### ISSUE TITLE
laravel5.7安装后登陆就报错

### ISSUE THREAD

**Issue by fine129** [moell-peng/mojito#6]
首先“将 admin.js 添加到 webpack.mix.js”，格式不对，按照注释掉的“   //.js('resources/js/admin.js', 'public/js') laravel5.7+”添加后，启动运行，登陆时报错：

admin.js:12489 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at admin.js:12489
(anonymous) @ admin.js:12489
Promise.then (async)
(anonymous) @ 6.js:147
(anonymous) @ admin.js:35647
(anonymous) @ admin.js:35968
complete @ admin.js:60579
(anonymous) @ admin.js:60715
next @ admin.js:621
next @ admin.js:589
cb @ admin.js:60663
required @ admin.js:62321
(anonymous) @ admin.js:60706
next @ admin.js:587
asyncSerialArray @ admin.js:593
(anonymous) @ admin.js:627
asyncMap @ admin.js:624
validate @ admin.js:60631
validate @ admin.js:35964
(anonymous) @ admin.js:35641
validate @ admin.js:35640
submitForm @ 6.js:143
click @ 6.js:234
invoker @ admin.js:2694
Vue.$emit @ admin.js:3205
handleClick @ admin.js:25560
invoker @ admin.js:2694
fn._withTask.fn._withTask @ admin.js:2493

无法使用运转，白白浪费功夫，真是无奈，这个想法解决吧。

**Comment by fine129** [comment]
试着运行了  npm run production 后，登陆可以了，真是怪异，，，，

**Comment by moell-peng** [comment]
@fine129 会不会添加密码授予客户端的 ID 和 secret 在 `npm run production` 或 `npm run watch ` 中止之后
