### ISSUE TITLE
安装后登录失败

### ISSUE THREAD

**Issue by qin-zhuopu** [moell-peng/mojito#9]
php artisan passport:install
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client secret: ZfkFZ9Q2MKoHPCPNNVaqkwImFc4ma07abClKX4b9
Password grant client created successfully.
Client ID: 2
Client secret: 5gYmgJnvGYDuk56GzZ9UwlWrRWdK9utJMCy2e5bB

cat resources/config/index.js
export default {
  admin: {
    authorize: {
      clientId: 1,
      clientSecret: ZfkFZ9Q2MKoHPCPNNVaqkwImFc4ma07abClKX4b9
    }
}

登录时, 输入用户名 admin@gmail.com 密码 ZfkFZ9Q2MKoHPCPNNVaqkwImFc4ma07abClKX4b9 返回401 
{"error":"invalid_client","message":"Client authentication failed"}

**Comment by qin-zhuopu** [comment]
这个文档写的啊, 真的是错误百出, 浪费了我两天的时间.

**Comment by moell-peng** [comment]
请仔细查阅文档：
![qq 20190122140952](https://user-images.githubusercontent.com/12830061/51515697-a91cd700-1e4f-11e9-8d93-95a9a413e35e.png)
1，  明确要求的是密码授予客户端的 ID 和 secret ，你执行的passport:install， ID = 2 ,已经明确告诉你 Password grant client created successfully. 这才是你所需要的ID 和  secret 。
```
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 1
Client secret: ZfkFZ9Q2MKoHPCPNNVaqkwImFc4ma07abClKX4b9

Password grant client created successfully.
Client ID: 2
Client secret: 5gYmgJnvGYDuk56GzZ9UwlWrRWdK9utJMCy2e5bB
```

2. 登录密码不是明确告诉你密码是 secret  了吗？ 为什么会理解成passport 的 secret .

**Comment by qin-zhuopu** [comment]
这个实在是太容易引起误解了. 提了个pr, 请酌情处理. 
希望能让后来人更容易上手.

**Comment by yuzhewo** [comment]
我看不懂到底需要什么账号密码进行登陆，自己在研究下吧。
